# render.yaml

services:
  - type: web
    name: pokebot-worker
    env: python
    port: 10000
    # La commande d'installation et de démarrage est prise directement à partir des autres fichiers de votre dépôt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free